### ISSUE TITLE
Terminal Issue

### ISSUE THREAD

**Issue by SrMoroxide** [valentin-marquez/LethalMissions#1]
Hello!
It seems that the terminal has a small detail, where the text inside the screen appears a little higher than it should be, superimposing next to the price value as shown in the image.

![image](https://github.com/valentin-marquez/LethalMissions/assets/152836693/0bde0d48-d24e-463b-b6c2-bed0fc27311d)

**Comment by valentin-marquez** [comment]
Thanks for the report. The problem of overlapping credits in the terminal is related to the [LethalAPI.TerminalCommands](https://github.com/LethalCompany/LethalAPI.TerminalCommands) dependency I am using.

**Comment by valentin-marquez** [comment]
LethalApi.terminal dependency was updated, the update fixed this bug.
