### ISSUE TITLE
[Bug] No notification

### ISSUE THREAD

**Issue by darkanx** [valentin-marquez/LethalMissions#10]
**Description of the Issue:**

In the newest update, there is no longer a notification popup when the ship lands informing you that "new missions are available". Settings in config are correct, with NewMissionNotify=true set.

**Additional Information:**

- Mod Version: v1.1.0
- Language Setting: en
- Operating System: win10
- Tested in a virgin profile with only this mod installed with default settings

**Comment by valentin-marquez** [comment]
Will be corrected for version 1.1.1
