### ISSUE TITLE
Out of sync of the cost of things - with mods for loot

### ISSUE THREAD

**Issue by Paradox75831004** [valentin-marquez/LethalMissions#11]
**Description of the problem:**

In the combination of our build, where a separate loot is added and so on. For some reason, when we enter the complex, some of the items cost 0 credits (the HOST SEES THE FULL PRICE). When we bring loot to the ship, the players who are not the host do not see the price at all. After takeoff, the next map is loaded - generation gets up due to out-of-sync.

If the host recreates the game with the loot that cost 0 credits, the loot is loaded and shows its real price.

**Expected behavior:**

To fix the out-of-sync so that everyone can see the price of the loot and the loading of the next card

**Additional information:**

- Nozz-Lethal_Missions-1.1.1
- Language settings: en
- Windows 10
- Our build profile code: LETHAL_LONERS - 018d39a7-c97c-0894-c291-c96af2492a9b

**Screenshots (if applicable):**

![image](https://github.com/valentin-marquez/LethalMissions/assets/72872478/bd8ee2b4-655e-4ade-8873-a4e74e1e83bd)
![image](https://github.com/valentin-marquez/LethalMissions/assets/72872478/e8cc52ad-9065-4d58-b843-62e2fbc083ec)

**Comment by valentin-marquez** [comment]
this is rare and should not happen, since the mod does not modify anything of the game objects, it only works by reading the game information. therefore this should not be caused by the mod, I will still take a look and respond as soon as possible.

**Comment by Paradox75831004** [comment]
> this is rare and should not happen, since the mod does not modify anything of the game objects, it only works by reading the game information. therefore this should not be caused by the mod, I will still take a look and respond as soon as possible.

After disabling your mod, everything became fine.  I think this is a sign and the problem lies somewhere close...

**Comment by Paradox75831004** [comment]
Add a random appearance of the mission from 1 to 3. Not just 3 at once.

**Comment by Paradox75831004** [comment]
![image](https://github.com/valentin-marquez/LethalMissions/assets/72872478/4f9c17c1-b4af-445e-8225-377dcab12e74)
Can you specify the mod version in the config? To make it easier to identify and so on. I will be grateful! (add a comment from above)

**Comment by Paradox75831004** [comment]
I recently repaired the valve, the mission was with him. But he didn't check in to the task - what did I fix or someone else

**Comment by Paradox75831004** [comment]
To display the keys, I had to manually delete the config - after which everything worked and showed how it should

**Comment by Paradox75831004** [comment]
When I die (playing alone), a window with missions and rewards appears in front of me for a split second and abruptly disappears - I don't even have time to look. Is there any way to set up a reward alert for the dead?

**Comment by Paradox75831004** [comment]
The problem still remains when someone brings in an item that costs nothing. The download to the next card stops
v1.1.4
018d45c6-147e-ad68-c79b-1a7b243177ac
![Uploading image.png…]()

**Comment by Paradox75831004** [comment]
I'm sorry, I can't figure out what the problem is at all.
