### ISSUE TITLE
Only the host sees the missions?

### ISSUE THREAD

**Issue by SrMoroxide** [valentin-marquez/LethalMissions#3]
I was playing with several people, and when they tried to access the mission field, they got the message that they do not have enough rank, is that only the host can see it or is there something else I don't know?

**Comment by valentin-marquez** [comment]
This issue has been addressed in commit [5637c28](https://github.com/valentin-marquez/LethalMissions/commit/5637c28d7654acbc07ea52c95596136744ae3c32). In this commit, we've made changes to ensure that missions are visible to all players, not just the host.

Therefore, I will proceed to close this issue. If you encounter further related issues, please feel free to reopen this or create a new one. Thank you!
