### ISSUE TITLE
Always getting message about range of the factories

### ISSUE THREAD

**Issue by perfect-deform** [valentin-marquez/LethalMissions#6]
Always getting message about range of the factories. Both Host and Clients. In the factory or out.
Problem only appears in multiplayer, works nice in local.
![image](https://github.com/valentin-marquez/LethalMissions/assets/60361408/f0aeb70b-fec8-452d-a20a-ca0ff010f2f1)

**Comment by valentin-marquez** [comment]
Apparently this happens when the host creates a game and then goes back to the main menu to create it again, this would cause other players to not be able to see the missions and also information is needed to reproduce the problem.

**Comment by valentin-marquez** [comment]
This issue has been addressed in commit [5637c28](https://github.com/valentin-marquez/LethalMissions/commit/5637c28d7654acbc07ea52c95596136744ae3c32). In this commit, we've made changes to ensure that missions are visible to all players, not just the host.

Therefore, I will proceed to close this issue. If you encounter further related issues, please feel free to reopen this or create a new one. Thank you!
