### ISSUE TITLE
plears cant join if mod is installed

### ISSUE THREAD

**Issue by g7755726** [valentin-marquez/LethalMissions#7]
players cant join my lobby when mod is installed

**Comment by valentin-marquez** [comment]
thanks for reporting the problem, but to know exactly what is happening, I need the LogOutput.log file.

or write down the steps to reproduce the problem.

**Comment by g7755726** [comment]
I installed the mod via the thunderstore app then launched the game, closed the game and then edited the config from 2 to 3, saved and relaunched and no one wasnt able to join me they got an error has ouccured but as soon as they try to join. When they turn it off they are able to join

**Comment by valentin-marquez** [comment]
it seems that there is a problem with getting the missions. it seems that all players have to have the same number of missions configured. Thanks for the report.

**Comment by valentin-marquez** [comment]
after trying to reproduce the problem for a while, I was unable to do so. I leave the problem open to see if it happens to someone else in the future.

**Comment by g7755726** [comment]
You will need a friend to reproduce it, have you tried having a friend join whilenthey have it disabled but you have it enabled?
