### ISSUE TITLE
I propose an idea

### ISSUE THREAD

**Issue by Paradox75831004** [valentin-marquez/LethalMissions#9]
Your mod is very beautiful, it somewhat resembled the old version of Employeeassignment. What if I add an initial alert - that there are missions and press "J" to view them. The probability of missions, and sometimes the complete absence of them

**Comment by Paradox75831004** [comment]
Is it possible for the dead to watch the progress of the mission? For some reason I couldn't... (when I was playing alone)

**Comment by Paradox75831004** [comment]
Apologize. Sometimes there is a lack of missions. I just didn't know about it.

**Comment by Paradox75831004** [comment]
The keys are the vanilla part of the game. You can't buy them, yes. I added them using a mod. But isn't it possible to add them, or is there a problem with that? - because it's loot

**Comment by Paradox75831004** [comment]
If I remember something else from vanilla, I'll let you know about it

**Comment by valentin-marquez** [comment]
Yes, it is possible, I will add it as a configuration for a possible 1.1.1.

**Comment by Paradox75831004** [comment]
LETHAL_LONERS - 018d3b7a-efea-f08e-5093-0824b2ded467 missions do not work in our build for players who are not the host. The problem is still the same

disable log mods that hide errors. Help me figure out the problem in this one. I really want to add this to the mod assembly so that it works stably
